"""baseline schema

Revision ID: 0001
Revises:
Create Date: 2026-09-20 19:27:18.538374
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# JSON on SQLite, JSONB on PostgreSQL (mirrors cews.database.models.JSON_TYPE).
JSON_TYPE = sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql")

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "anomalies",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("anomaly_date", sa.Date(), nullable=False),
        sa.Column("entity_type", sa.String(length=32), nullable=False),
        sa.Column("entity_id", sa.Integer(), nullable=False),
        sa.Column("metric", sa.String(length=64), nullable=False),
        sa.Column("observed_value", sa.Float(), nullable=False),
        sa.Column("expected_lower", sa.Float(), nullable=False),
        sa.Column("expected_upper", sa.Float(), nullable=False),
        sa.Column("deviation", sa.Float(), nullable=False),
        sa.Column("method", sa.String(length=32), nullable=False),
        sa.Column("anomaly_class", sa.String(length=32), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("evidence_json", JSON_TYPE, nullable=True),
        sa.Column("is_synthetic", sa.Boolean(), nullable=False),
        sa.CheckConstraint(
            "confidence >= 0 AND confidence <= 100", name=op.f("ck_anomalies_confidence_range")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_anomalies")),
    )
    op.create_index(op.f("ix_anomalies_anomaly_date"), "anomalies", ["anomaly_date"], unique=False)
    op.create_index("ix_anomalies_entity", "anomalies", ["entity_type", "entity_id"], unique=False)
    op.create_table(
        "evaluation_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("evaluation_id", sa.String(length=64), nullable=False),
        sa.Column("evaluation_type", sa.String(length=32), nullable=False),
        sa.Column("evaluation_date", sa.Date(), nullable=False),
        sa.Column("period_start", sa.Date(), nullable=True),
        sa.Column("period_end", sa.Date(), nullable=True),
        sa.Column("configuration_json", JSON_TYPE, nullable=False),
        sa.Column("metrics_json", JSON_TYPE, nullable=False),
        sa.Column("is_synthetic", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_evaluation_runs")),
        sa.UniqueConstraint("evaluation_id", name=op.f("uq_evaluation_runs_evaluation_id")),
    )
    op.create_index(
        op.f("ix_evaluation_runs_evaluation_date"),
        "evaluation_runs",
        ["evaluation_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_evaluation_runs_evaluation_type"),
        "evaluation_runs",
        ["evaluation_type"],
        unique=False,
    )
    op.create_table(
        "feature_values",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("feature_date", sa.Date(), nullable=False),
        sa.Column("entity_type", sa.String(length=32), nullable=False),
        sa.Column("entity_id", sa.Integer(), nullable=False),
        sa.Column("context_key", sa.String(length=64), nullable=False),
        sa.Column("feature_name", sa.String(length=64), nullable=False),
        sa.Column("raw_value", sa.Float(), nullable=True),
        sa.Column("normalized_value", sa.Float(), nullable=True),
        sa.Column("normalization_method", sa.String(length=32), nullable=True),
        sa.Column("comparison_cohort", sa.String(length=128), nullable=False),
        sa.Column("cohort_size", sa.Integer(), nullable=True),
        sa.Column("sample_size", sa.Integer(), nullable=True),
        sa.Column("computed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_synthetic", sa.Boolean(), nullable=False),
        sa.CheckConstraint(
            "normalized_value IS NULL OR (normalized_value >= 0 AND normalized_value <= 100)",
            name=op.f("ck_feature_values_normalized_range"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_feature_values")),
        sa.UniqueConstraint(
            "feature_date",
            "entity_type",
            "entity_id",
            "context_key",
            "feature_name",
            "comparison_cohort",
            name="uq_feature_values_key",
        ),
    )
    op.create_index(
        "ix_feature_values_entity", "feature_values", ["entity_type", "entity_id"], unique=False
    )
    op.create_index(
        op.f("ix_feature_values_feature_date"), "feature_values", ["feature_date"], unique=False
    )
    op.create_table(
        "forecasts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("entity_type", sa.String(length=32), nullable=False),
        sa.Column("entity_id", sa.Integer(), nullable=False),
        sa.Column("source_type", sa.String(length=32), nullable=False),
        sa.Column("forecast_date", sa.Date(), nullable=False),
        sa.Column("target_period", sa.Date(), nullable=False),
        sa.Column("predicted_value", sa.Float(), nullable=False),
        sa.Column("lower_bound", sa.Float(), nullable=False),
        sa.Column("upper_bound", sa.Float(), nullable=False),
        sa.Column("model_name", sa.String(length=64), nullable=False),
        sa.Column("backtest_metric_name", sa.String(length=32), nullable=True),
        sa.Column("backtest_metric", sa.Float(), nullable=True),
        sa.Column("training_months", sa.Integer(), nullable=True),
        sa.Column("is_synthetic", sa.Boolean(), nullable=False),
        sa.CheckConstraint("lower_bound <= upper_bound", name=op.f("ck_forecasts_bounds_ordered")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_forecasts")),
        sa.UniqueConstraint(
            "entity_type",
            "entity_id",
            "source_type",
            "forecast_date",
            "target_period",
            name="uq_forecasts_key",
        ),
    )
    op.create_index(
        op.f("ix_forecasts_forecast_date"), "forecasts", ["forecast_date"], unique=False
    )
    op.create_table(
        "ingestion_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("job_id", sa.String(length=64), nullable=False),
        sa.Column("source", sa.String(length=64), nullable=False),
        sa.Column("start_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("records_requested", sa.Integer(), nullable=False),
        sa.Column("records_received", sa.Integer(), nullable=False),
        sa.Column("records_inserted", sa.Integer(), nullable=False),
        sa.Column("records_updated", sa.Integer(), nullable=False),
        sa.Column("records_skipped", sa.Integer(), nullable=False),
        sa.Column("duplicate_count", sa.Integer(), nullable=False),
        sa.Column("error_count", sa.Integer(), nullable=False),
        sa.Column("checkpoint_json", JSON_TYPE, nullable=True),
        sa.Column("warnings_json", JSON_TYPE, nullable=True),
        sa.Column("error_summary", sa.Text(), nullable=True),
        sa.Column("is_synthetic", sa.Boolean(), nullable=False),
        sa.CheckConstraint(
            "status IN ('running', 'succeeded', 'partial', 'failed', 'skipped')",
            name=op.f("ck_ingestion_runs_status"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ingestion_runs")),
    )
    op.create_index(op.f("ix_ingestion_runs_job_id"), "ingestion_runs", ["job_id"], unique=False)
    op.create_index(op.f("ix_ingestion_runs_source"), "ingestion_runs", ["source"], unique=False)
    op.create_index(
        op.f("ix_ingestion_runs_start_time"), "ingestion_runs", ["start_time"], unique=False
    )
    op.create_table(
        "insights",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("insight_date", sa.Date(), nullable=False),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("insight_type", sa.String(length=32), nullable=False),
        sa.Column("entity_type", sa.String(length=32), nullable=False),
        sa.Column("entity_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("observed_fact", sa.Text(), nullable=False),
        sa.Column("interpretation", sa.Text(), nullable=False),
        sa.Column("recommended_review", sa.Text(), nullable=False),
        sa.Column("confidence_score", sa.Float(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("dedupe_key", sa.String(length=128), nullable=False),
        sa.Column("is_synthetic", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "confidence_score >= 0 AND confidence_score <= 100",
            name=op.f("ck_insights_confidence_range"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_insights")),
    )
    op.create_index(op.f("ix_insights_dedupe_key"), "insights", ["dedupe_key"], unique=False)
    op.create_index("ix_insights_entity", "insights", ["entity_type", "entity_id"], unique=False)
    op.create_index(op.f("ix_insights_insight_date"), "insights", ["insight_date"], unique=False)
    op.create_table(
        "job_locks",
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("owner", sa.String(length=64), nullable=False),
        sa.Column("acquired_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("name", name=op.f("pk_job_locks")),
    )
    op.create_table(
        "job_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("job_id", sa.String(length=64), nullable=False),
        sa.Column("job_name", sa.String(length=64), nullable=False),
        sa.Column("trigger", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("dry_run", sa.Boolean(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("summary_json", JSON_TYPE, nullable=True),
        sa.Column("error_summary", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "status IN ('running', 'succeeded', 'partial', 'failed', 'skipped')",
            name=op.f("ck_job_runs_status"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_job_runs")),
        sa.UniqueConstraint("job_id", name=op.f("uq_job_runs_job_id")),
    )
    op.create_index(op.f("ix_job_runs_job_name"), "job_runs", ["job_name"], unique=False)
    op.create_index(op.f("ix_job_runs_started_at"), "job_runs", ["started_at"], unique=False)
    op.create_table(
        "organizations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("canonical_name", sa.String(length=255), nullable=False),
        sa.Column("normalized_name", sa.String(length=255), nullable=False),
        sa.Column("organization_type", sa.String(length=32), nullable=False),
        sa.Column("country", sa.String(length=64), nullable=True),
        sa.Column("website", sa.String(length=512), nullable=True),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("discovered_automatically", sa.Boolean(), nullable=False),
        sa.Column("manually_included", sa.Boolean(), nullable=False),
        sa.Column("manually_excluded", sa.Boolean(), nullable=False),
        sa.Column("is_synthetic", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["organizations.id"],
            name=op.f("fk_organizations_parent_id_organizations"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_organizations")),
        sa.UniqueConstraint("canonical_name", name=op.f("uq_organizations_canonical_name")),
    )
    op.create_index(
        op.f("ix_organizations_is_synthetic"), "organizations", ["is_synthetic"], unique=False
    )
    op.create_index(
        op.f("ix_organizations_normalized_name"), "organizations", ["normalized_name"], unique=False
    )
    op.create_index(
        op.f("ix_organizations_parent_id"), "organizations", ["parent_id"], unique=False
    )
    op.create_table(
        "review_queue",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("queue_type", sa.String(length=32), nullable=False),
        sa.Column("subject_ref", sa.String(length=255), nullable=False),
        sa.Column("payload_json", JSON_TYPE, nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('pending', 'accepted', 'rejected')", name=op.f("ck_review_queue_status")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_review_queue")),
        sa.UniqueConstraint("queue_type", "subject_ref", name="uq_review_queue_subject"),
    )
    op.create_index(
        op.f("ix_review_queue_queue_type"), "review_queue", ["queue_type"], unique=False
    )
    op.create_index(op.f("ix_review_queue_status"), "review_queue", ["status"], unique=False)
    op.create_table(
        "scores",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("score_date", sa.Date(), nullable=False),
        sa.Column("entity_type", sa.String(length=32), nullable=False),
        sa.Column("entity_id", sa.Integer(), nullable=False),
        sa.Column("context_key", sa.String(length=64), nullable=False),
        sa.Column("score_type", sa.String(length=32), nullable=False),
        sa.Column("score_value", sa.Float(), nullable=False),
        sa.Column("confidence_score", sa.Float(), nullable=False),
        sa.Column("component_json", JSON_TYPE, nullable=False),
        sa.Column("scoring_version", sa.String(length=32), nullable=False),
        sa.Column("is_synthetic", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "confidence_score >= 0 AND confidence_score <= 100",
            name=op.f("ck_scores_confidence_range"),
        ),
        sa.CheckConstraint(
            "score_value >= 0 AND score_value <= 100", name=op.f("ck_scores_score_range")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scores")),
        sa.UniqueConstraint(
            "score_date",
            "entity_type",
            "entity_id",
            "context_key",
            "score_type",
            "scoring_version",
            name="uq_scores_key",
        ),
    )
    op.create_index("ix_scores_entity", "scores", ["entity_type", "entity_id"], unique=False)
    op.create_index(op.f("ix_scores_score_date"), "scores", ["score_date"], unique=False)
    op.create_table(
        "source_checkpoints",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source", sa.String(length=64), nullable=False),
        sa.Column("checkpoint_json", JSON_TYPE, nullable=True),
        sa.Column("last_attempted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_success_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_status", sa.String(length=16), nullable=True),
        sa.Column("consecutive_failures", sa.Integer(), nullable=False),
        sa.Column("circuit_open_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_source_checkpoints")),
        sa.UniqueConstraint("source", name=op.f("uq_source_checkpoints_source")),
    )
    op.create_table(
        "source_records",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source", sa.String(length=64), nullable=False),
        sa.Column("source_record_id", sa.String(length=256), nullable=False),
        sa.Column("record_type", sa.String(length=32), nullable=False),
        sa.Column("source_url", sa.String(length=1024), nullable=True),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("abstract", sa.Text(), nullable=True),
        sa.Column("raw_payload_json", JSON_TYPE, nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at_source", sa.DateTime(timezone=True), nullable=True),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("processing_status", sa.String(length=32), nullable=False),
        sa.Column("is_synthetic", sa.Boolean(), nullable=False),
        sa.CheckConstraint(
            "processing_status IN ('new', 'normalized', 'failed')",
            name=op.f("ck_source_records_processing_status"),
        ),
        sa.CheckConstraint(
            "record_type IN ('clinical_trial', 'publication', 'patent', 'funding', 'announcement')",
            name=op.f("ck_source_records_record_type"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_source_records")),
        sa.UniqueConstraint("source", "source_record_id", name="uq_source_records_source_record"),
    )
    op.create_index(
        op.f("ix_source_records_content_hash"), "source_records", ["content_hash"], unique=False
    )
    op.create_index(
        op.f("ix_source_records_fetched_at"), "source_records", ["fetched_at"], unique=False
    )
    op.create_index(
        op.f("ix_source_records_is_synthetic"), "source_records", ["is_synthetic"], unique=False
    )
    op.create_index(
        op.f("ix_source_records_processing_status"),
        "source_records",
        ["processing_status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_source_records_published_at"), "source_records", ["published_at"], unique=False
    )
    op.create_index("ix_source_records_source_url", "source_records", ["source_url"], unique=False)
    op.create_index(
        "ix_source_records_type_published",
        "source_records",
        ["record_type", "published_at"],
        unique=False,
    )
    op.create_table(
        "therapeutic_areas",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("canonical_name", sa.String(length=255), nullable=False),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["therapeutic_areas.id"],
            name=op.f("fk_therapeutic_areas_parent_id_therapeutic_areas"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_therapeutic_areas")),
        sa.UniqueConstraint("canonical_name", name=op.f("uq_therapeutic_areas_canonical_name")),
        sa.UniqueConstraint("key", name=op.f("uq_therapeutic_areas_key")),
    )
    op.create_index(
        op.f("ix_therapeutic_areas_parent_id"), "therapeutic_areas", ["parent_id"], unique=False
    )
    op.create_table(
        "ai_extractions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source_record_id", sa.Integer(), nullable=False),
        sa.Column("extraction_type", sa.String(length=32), nullable=False),
        sa.Column("model", sa.String(length=128), nullable=False),
        sa.Column("prompt_version", sa.String(length=32), nullable=False),
        sa.Column("output_json", JSON_TYPE, nullable=False),
        sa.Column("grounded", sa.Boolean(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_record_id"],
            ["source_records.id"],
            name=op.f("fk_ai_extractions_source_record_id_source_records"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_extractions")),
        sa.UniqueConstraint(
            "source_record_id",
            "extraction_type",
            "model",
            "prompt_version",
            name="uq_ai_extractions_key",
        ),
    )
    op.create_index(
        op.f("ix_ai_extractions_source_record_id"),
        "ai_extractions",
        ["source_record_id"],
        unique=False,
    )
    op.create_table(
        "alert_reviews",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("insight_id", sa.Integer(), nullable=False),
        sa.Column("rating", sa.String(length=32), nullable=False),
        sa.Column("reviewer", sa.String(length=128), nullable=True),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "rating IN ('relevant', 'not_relevant', 'duplicate', 'too_late', 'insufficient_evidence', 'needs_investigation')",
            name=op.f("ck_alert_reviews_rating"),
        ),
        sa.ForeignKeyConstraint(
            ["insight_id"],
            ["insights.id"],
            name=op.f("fk_alert_reviews_insight_id_insights"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_alert_reviews")),
    )
    op.create_index(
        op.f("ix_alert_reviews_insight_id"), "alert_reviews", ["insight_id"], unique=False
    )
    op.create_table(
        "announcements",
        sa.Column("source_record_id", sa.Integer(), nullable=False),
        sa.Column("organization_name", sa.String(length=255), nullable=True),
        sa.Column("organization_id", sa.Integer(), nullable=True),
        sa.Column("announcement_type", sa.String(length=64), nullable=True),
        sa.Column("announcement_date", sa.Date(), nullable=True),
        sa.Column("partner_organizations", JSON_TYPE, nullable=True),
        sa.Column("detected_topics", JSON_TYPE, nullable=True),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_announcements_organization_id_organizations"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["source_record_id"],
            ["source_records.id"],
            name=op.f("fk_announcements_source_record_id_source_records"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("source_record_id", name=op.f("pk_announcements")),
    )
    op.create_index(
        op.f("ix_announcements_organization_id"), "announcements", ["organization_id"], unique=False
    )
    op.create_table(
        "clinical_trials",
        sa.Column("source_record_id", sa.Integer(), nullable=False),
        sa.Column("trial_identifier", sa.String(length=64), nullable=False),
        sa.Column("sponsor_name", sa.String(length=255), nullable=True),
        sa.Column("sponsor_organization_id", sa.Integer(), nullable=True),
        sa.Column("phase", sa.String(length=32), nullable=True),
        sa.Column("status", sa.String(length=64), nullable=True),
        sa.Column("enrollment", sa.Integer(), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("completion_date", sa.Date(), nullable=True),
        sa.Column("intervention", sa.Text(), nullable=True),
        sa.Column("condition", sa.Text(), nullable=True),
        sa.Column("countries", JSON_TYPE, nullable=True),
        sa.CheckConstraint(
            "enrollment IS NULL OR enrollment >= 0", name=op.f("ck_clinical_trials_enrollment")
        ),
        sa.ForeignKeyConstraint(
            ["source_record_id"],
            ["source_records.id"],
            name=op.f("fk_clinical_trials_source_record_id_source_records"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["sponsor_organization_id"],
            ["organizations.id"],
            name=op.f("fk_clinical_trials_sponsor_organization_id_organizations"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("source_record_id", name=op.f("pk_clinical_trials")),
    )
    op.create_index(
        op.f("ix_clinical_trials_sponsor_organization_id"),
        "clinical_trials",
        ["sponsor_organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_clinical_trials_trial_identifier"),
        "clinical_trials",
        ["trial_identifier"],
        unique=False,
    )
    op.create_table(
        "funding_awards",
        sa.Column("source_record_id", sa.Integer(), nullable=False),
        sa.Column("award_identifier", sa.String(length=64), nullable=False),
        sa.Column("recipient_name", sa.String(length=255), nullable=True),
        sa.Column("recipient_organization_id", sa.Integer(), nullable=True),
        sa.Column("agency", sa.String(length=255), nullable=True),
        sa.Column("amount", sa.Float(), nullable=True),
        sa.Column("currency", sa.String(length=8), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.CheckConstraint("amount IS NULL OR amount >= 0", name=op.f("ck_funding_awards_amount")),
        sa.ForeignKeyConstraint(
            ["recipient_organization_id"],
            ["organizations.id"],
            name=op.f("fk_funding_awards_recipient_organization_id_organizations"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["source_record_id"],
            ["source_records.id"],
            name=op.f("fk_funding_awards_source_record_id_source_records"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("source_record_id", name=op.f("pk_funding_awards")),
    )
    op.create_index(
        op.f("ix_funding_awards_award_identifier"),
        "funding_awards",
        ["award_identifier"],
        unique=False,
    )
    op.create_index(
        op.f("ix_funding_awards_recipient_organization_id"),
        "funding_awards",
        ["recipient_organization_id"],
        unique=False,
    )
    op.create_table(
        "insight_evidence",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("insight_id", sa.Integer(), nullable=False),
        sa.Column("source_record_id", sa.Integer(), nullable=False),
        sa.Column("evidence_role", sa.String(length=32), nullable=False),
        sa.Column("evidence_weight", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["insight_id"],
            ["insights.id"],
            name=op.f("fk_insight_evidence_insight_id_insights"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_record_id"],
            ["source_records.id"],
            name=op.f("fk_insight_evidence_source_record_id_source_records"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_insight_evidence")),
        sa.UniqueConstraint(
            "insight_id", "source_record_id", "evidence_role", name="uq_insight_evidence_link"
        ),
    )
    op.create_index(
        op.f("ix_insight_evidence_insight_id"), "insight_evidence", ["insight_id"], unique=False
    )
    op.create_index(
        op.f("ix_insight_evidence_source_record_id"),
        "insight_evidence",
        ["source_record_id"],
        unique=False,
    )
    op.create_table(
        "organization_aliases",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("organization_id", sa.Integer(), nullable=False),
        sa.Column("alias", sa.String(length=255), nullable=False),
        sa.Column("normalized_alias", sa.String(length=255), nullable=False),
        sa.Column("alias_type", sa.String(length=32), nullable=False),
        sa.Column("match_method", sa.String(length=32), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.CheckConstraint(
            "confidence >= 0 AND confidence <= 1",
            name=op.f("ck_organization_aliases_confidence_range"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_organization_aliases_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_organization_aliases")),
        sa.UniqueConstraint("organization_id", "normalized_alias", name="uq_org_aliases_org_alias"),
    )
    op.create_index(
        op.f("ix_organization_aliases_normalized_alias"),
        "organization_aliases",
        ["normalized_alias"],
        unique=False,
    )
    op.create_index(
        op.f("ix_organization_aliases_organization_id"),
        "organization_aliases",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "patents",
        sa.Column("source_record_id", sa.Integer(), nullable=False),
        sa.Column("patent_identifier", sa.String(length=64), nullable=False),
        sa.Column("application_date", sa.Date(), nullable=True),
        sa.Column("publication_date", sa.Date(), nullable=True),
        sa.Column("grant_date", sa.Date(), nullable=True),
        sa.Column("assignee_name", sa.String(length=255), nullable=True),
        sa.Column("assignee_organization_id", sa.Integer(), nullable=True),
        sa.Column("inventors", JSON_TYPE, nullable=True),
        sa.Column("patent_classifications", JSON_TYPE, nullable=True),
        sa.Column("patent_family_id", sa.String(length=64), nullable=True),
        sa.Column("legal_status", sa.String(length=64), nullable=True),
        sa.ForeignKeyConstraint(
            ["assignee_organization_id"],
            ["organizations.id"],
            name=op.f("fk_patents_assignee_organization_id_organizations"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["source_record_id"],
            ["source_records.id"],
            name=op.f("fk_patents_source_record_id_source_records"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("source_record_id", name=op.f("pk_patents")),
    )
    op.create_index(
        op.f("ix_patents_assignee_organization_id"),
        "patents",
        ["assignee_organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_patents_patent_family_id"), "patents", ["patent_family_id"], unique=False
    )
    op.create_index(
        op.f("ix_patents_patent_identifier"), "patents", ["patent_identifier"], unique=False
    )
    op.create_table(
        "publications",
        sa.Column("source_record_id", sa.Integer(), nullable=False),
        sa.Column("publication_identifier", sa.String(length=128), nullable=False),
        sa.Column("journal", sa.String(length=255), nullable=True),
        sa.Column("publication_date", sa.Date(), nullable=True),
        sa.Column("authors", JSON_TYPE, nullable=True),
        sa.Column("affiliations", JSON_TYPE, nullable=True),
        sa.Column("citation_count", sa.Integer(), nullable=True),
        sa.Column("publication_type", sa.String(length=64), nullable=True),
        sa.ForeignKeyConstraint(
            ["source_record_id"],
            ["source_records.id"],
            name=op.f("fk_publications_source_record_id_source_records"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("source_record_id", name=op.f("pk_publications")),
    )
    op.create_index(
        op.f("ix_publications_publication_identifier"),
        "publications",
        ["publication_identifier"],
        unique=False,
    )
    op.create_table(
        "record_organizations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source_record_id", sa.Integer(), nullable=False),
        sa.Column("organization_id", sa.Integer(), nullable=False),
        sa.Column("relationship_type", sa.String(length=32), nullable=False),
        sa.Column("match_method", sa.String(length=32), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.CheckConstraint(
            "confidence >= 0 AND confidence <= 1",
            name=op.f("ck_record_organizations_confidence_range"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_record_organizations_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_record_id"],
            ["source_records.id"],
            name=op.f("fk_record_organizations_source_record_id_source_records"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_record_organizations")),
        sa.UniqueConstraint(
            "source_record_id", "organization_id", "relationship_type", name="uq_record_orgs_link"
        ),
    )
    op.create_index(
        op.f("ix_record_organizations_organization_id"),
        "record_organizations",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_record_organizations_source_record_id"),
        "record_organizations",
        ["source_record_id"],
        unique=False,
    )
    op.create_table(
        "topics",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("key", sa.String(length=128), nullable=False),
        sa.Column("canonical_name", sa.String(length=255), nullable=False),
        sa.Column("topic_type", sa.String(length=32), nullable=False),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("therapeutic_area_id", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.CheckConstraint(
            "status IN ('active', 'pending_review', 'rejected')", name=op.f("ck_topics_status")
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["topics.id"],
            name=op.f("fk_topics_parent_id_topics"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["therapeutic_area_id"],
            ["therapeutic_areas.id"],
            name=op.f("fk_topics_therapeutic_area_id_therapeutic_areas"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_topics")),
        sa.UniqueConstraint("key", name=op.f("uq_topics_key")),
    )
    op.create_index(op.f("ix_topics_parent_id"), "topics", ["parent_id"], unique=False)
    op.create_index(
        op.f("ix_topics_therapeutic_area_id"), "topics", ["therapeutic_area_id"], unique=False
    )
    op.create_table(
        "activity_aggregates",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("period", sa.Date(), nullable=False),
        sa.Column("period_type", sa.String(length=16), nullable=False),
        sa.Column("organization_id", sa.Integer(), nullable=True),
        sa.Column("topic_id", sa.Integer(), nullable=True),
        sa.Column("source_type", sa.String(length=32), nullable=False),
        sa.Column("activity_count", sa.Integer(), nullable=False),
        sa.Column("weighted_activity", sa.Float(), nullable=False),
        sa.Column("unique_record_count", sa.Integer(), nullable=False),
        sa.Column("is_synthetic", sa.Boolean(), nullable=False),
        sa.CheckConstraint(
            "period_type IN ('month', 'quarter', 'year')",
            name=op.f("ck_activity_aggregates_period_type"),
        ),
        sa.CheckConstraint(
            "source_type IN ('clinical_trial', 'publication', 'patent', 'funding', 'announcement')",
            name=op.f("ck_activity_aggregates_source_type"),
        ),
        sa.CheckConstraint(
            "activity_count >= 0", name=op.f("ck_activity_aggregates_activity_count")
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_activity_aggregates_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["topic_id"],
            ["topics.id"],
            name=op.f("fk_activity_aggregates_topic_id_topics"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_activity_aggregates")),
    )
    op.create_index(
        op.f("ix_activity_aggregates_organization_id"),
        "activity_aggregates",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_activity_aggregates_period"), "activity_aggregates", ["period"], unique=False
    )
    op.create_index(
        op.f("ix_activity_aggregates_topic_id"), "activity_aggregates", ["topic_id"], unique=False
    )
    op.create_table(
        "record_topics",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source_record_id", sa.Integer(), nullable=False),
        sa.Column("topic_id", sa.Integer(), nullable=False),
        sa.Column("matching_method", sa.String(length=32), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.CheckConstraint(
            "confidence >= 0 AND confidence <= 1", name=op.f("ck_record_topics_confidence_range")
        ),
        sa.ForeignKeyConstraint(
            ["source_record_id"],
            ["source_records.id"],
            name=op.f("fk_record_topics_source_record_id_source_records"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["topic_id"],
            ["topics.id"],
            name=op.f("fk_record_topics_topic_id_topics"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_record_topics")),
        sa.UniqueConstraint(
            "source_record_id", "topic_id", "matching_method", name="uq_record_topics_assignment"
        ),
    )
    op.create_index(
        op.f("ix_record_topics_source_record_id"),
        "record_topics",
        ["source_record_id"],
        unique=False,
    )
    op.create_index(op.f("ix_record_topics_topic_id"), "record_topics", ["topic_id"], unique=False)
    op.create_table(
        "topic_aliases",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("topic_id", sa.Integer(), nullable=False),
        sa.Column("alias", sa.String(length=255), nullable=False),
        sa.Column("matching_method", sa.String(length=32), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.CheckConstraint(
            "confidence >= 0 AND confidence <= 1", name=op.f("ck_topic_aliases_confidence_range")
        ),
        sa.ForeignKeyConstraint(
            ["topic_id"],
            ["topics.id"],
            name=op.f("fk_topic_aliases_topic_id_topics"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_topic_aliases")),
        sa.UniqueConstraint("topic_id", "alias", name="uq_topic_aliases_topic_alias"),
    )
    op.create_index(op.f("ix_topic_aliases_topic_id"), "topic_aliases", ["topic_id"], unique=False)
    # Unique key that treats NULL organization/topic as 0 (autogenerate cannot render this).
    op.create_index(
        "uq_activity_aggregates_key",
        "activity_aggregates",
        [
            "period",
            "period_type",
            "source_type",
            sa.text("coalesce(organization_id, 0)"),
            sa.text("coalesce(topic_id, 0)"),
        ],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("uq_activity_aggregates_key", table_name="activity_aggregates")
    op.drop_index(op.f("ix_topic_aliases_topic_id"), table_name="topic_aliases")
    op.drop_table("topic_aliases")
    op.drop_index(op.f("ix_record_topics_topic_id"), table_name="record_topics")
    op.drop_index(op.f("ix_record_topics_source_record_id"), table_name="record_topics")
    op.drop_table("record_topics")
    op.drop_index(op.f("ix_activity_aggregates_topic_id"), table_name="activity_aggregates")
    op.drop_index(op.f("ix_activity_aggregates_period"), table_name="activity_aggregates")
    op.drop_index(op.f("ix_activity_aggregates_organization_id"), table_name="activity_aggregates")
    op.drop_table("activity_aggregates")
    op.drop_index(op.f("ix_topics_therapeutic_area_id"), table_name="topics")
    op.drop_index(op.f("ix_topics_parent_id"), table_name="topics")
    op.drop_table("topics")
    op.drop_index(
        op.f("ix_record_organizations_source_record_id"), table_name="record_organizations"
    )
    op.drop_index(
        op.f("ix_record_organizations_organization_id"), table_name="record_organizations"
    )
    op.drop_table("record_organizations")
    op.drop_index(op.f("ix_publications_publication_identifier"), table_name="publications")
    op.drop_table("publications")
    op.drop_index(op.f("ix_patents_patent_identifier"), table_name="patents")
    op.drop_index(op.f("ix_patents_patent_family_id"), table_name="patents")
    op.drop_index(op.f("ix_patents_assignee_organization_id"), table_name="patents")
    op.drop_table("patents")
    op.drop_index(
        op.f("ix_organization_aliases_organization_id"), table_name="organization_aliases"
    )
    op.drop_index(
        op.f("ix_organization_aliases_normalized_alias"), table_name="organization_aliases"
    )
    op.drop_table("organization_aliases")
    op.drop_index(op.f("ix_insight_evidence_source_record_id"), table_name="insight_evidence")
    op.drop_index(op.f("ix_insight_evidence_insight_id"), table_name="insight_evidence")
    op.drop_table("insight_evidence")
    op.drop_index(op.f("ix_funding_awards_recipient_organization_id"), table_name="funding_awards")
    op.drop_index(op.f("ix_funding_awards_award_identifier"), table_name="funding_awards")
    op.drop_table("funding_awards")
    op.drop_index(op.f("ix_clinical_trials_trial_identifier"), table_name="clinical_trials")
    op.drop_index(op.f("ix_clinical_trials_sponsor_organization_id"), table_name="clinical_trials")
    op.drop_table("clinical_trials")
    op.drop_index(op.f("ix_announcements_organization_id"), table_name="announcements")
    op.drop_table("announcements")
    op.drop_index(op.f("ix_alert_reviews_insight_id"), table_name="alert_reviews")
    op.drop_table("alert_reviews")
    op.drop_index(op.f("ix_ai_extractions_source_record_id"), table_name="ai_extractions")
    op.drop_table("ai_extractions")
    op.drop_index(op.f("ix_therapeutic_areas_parent_id"), table_name="therapeutic_areas")
    op.drop_table("therapeutic_areas")
    op.drop_index("ix_source_records_type_published", table_name="source_records")
    op.drop_index("ix_source_records_source_url", table_name="source_records")
    op.drop_index(op.f("ix_source_records_published_at"), table_name="source_records")
    op.drop_index(op.f("ix_source_records_processing_status"), table_name="source_records")
    op.drop_index(op.f("ix_source_records_is_synthetic"), table_name="source_records")
    op.drop_index(op.f("ix_source_records_fetched_at"), table_name="source_records")
    op.drop_index(op.f("ix_source_records_content_hash"), table_name="source_records")
    op.drop_table("source_records")
    op.drop_table("source_checkpoints")
    op.drop_index(op.f("ix_scores_score_date"), table_name="scores")
    op.drop_index("ix_scores_entity", table_name="scores")
    op.drop_table("scores")
    op.drop_index(op.f("ix_review_queue_status"), table_name="review_queue")
    op.drop_index(op.f("ix_review_queue_queue_type"), table_name="review_queue")
    op.drop_table("review_queue")
    op.drop_index(op.f("ix_organizations_parent_id"), table_name="organizations")
    op.drop_index(op.f("ix_organizations_normalized_name"), table_name="organizations")
    op.drop_index(op.f("ix_organizations_is_synthetic"), table_name="organizations")
    op.drop_table("organizations")
    op.drop_index(op.f("ix_job_runs_started_at"), table_name="job_runs")
    op.drop_index(op.f("ix_job_runs_job_name"), table_name="job_runs")
    op.drop_table("job_runs")
    op.drop_table("job_locks")
    op.drop_index(op.f("ix_insights_insight_date"), table_name="insights")
    op.drop_index("ix_insights_entity", table_name="insights")
    op.drop_index(op.f("ix_insights_dedupe_key"), table_name="insights")
    op.drop_table("insights")
    op.drop_index(op.f("ix_ingestion_runs_start_time"), table_name="ingestion_runs")
    op.drop_index(op.f("ix_ingestion_runs_source"), table_name="ingestion_runs")
    op.drop_index(op.f("ix_ingestion_runs_job_id"), table_name="ingestion_runs")
    op.drop_table("ingestion_runs")
    op.drop_index(op.f("ix_forecasts_forecast_date"), table_name="forecasts")
    op.drop_table("forecasts")
    op.drop_index(op.f("ix_feature_values_feature_date"), table_name="feature_values")
    op.drop_index("ix_feature_values_entity", table_name="feature_values")
    op.drop_table("feature_values")
    op.drop_index(op.f("ix_evaluation_runs_evaluation_type"), table_name="evaluation_runs")
    op.drop_index(op.f("ix_evaluation_runs_evaluation_date"), table_name="evaluation_runs")
    op.drop_table("evaluation_runs")
    op.drop_index("ix_anomalies_entity", table_name="anomalies")
    op.drop_index(op.f("ix_anomalies_anomaly_date"), table_name="anomalies")
    op.drop_table("anomalies")
    # ### end Alembic commands ###
