"""ingestion checkpoint and audit fields

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-22 10:56:09.868042
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# JSON on SQLite, JSONB on PostgreSQL (mirrors cews.database.models.JSON_TYPE).
JSON_TYPE = sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql")

# revision identifiers, used by Alembic.
revision: str = "0002"
down_revision: Union[str, None] = "0001"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ingestion_runs", schema=None) as batch_op:
        batch_op.add_column(sa.Column("collection_mode", sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column("rate_limit_json", JSON_TYPE, nullable=True))

    with op.batch_alter_table("source_checkpoints", schema=None) as batch_op:
        batch_op.add_column(sa.Column("attempted_checkpoint_json", JSON_TYPE, nullable=True))
        batch_op.add_column(
            sa.Column("last_full_refresh_at", sa.DateTime(timezone=True), nullable=True)
        )
        batch_op.add_column(sa.Column("last_error", sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("source_checkpoints", schema=None) as batch_op:
        batch_op.drop_column("last_error")
        batch_op.drop_column("last_full_refresh_at")
        batch_op.drop_column("attempted_checkpoint_json")

    with op.batch_alter_table("ingestion_runs", schema=None) as batch_op:
        batch_op.drop_column("rate_limit_json")
        batch_op.drop_column("collection_mode")

    # ### end Alembic commands ###
